/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoreCalculatorRouteImport } from './routes/score-calculator'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YakuIndexRouteImport } from './routes/yaku/index'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as YakuIdRouteImport } from './routes/yaku/$id'
import { Route as QuizPlayRouteImport } from './routes/quiz/play'
import { Route as QuizHistoryRouteImport } from './routes/quiz/history'

const ScoreCalculatorRoute = ScoreCalculatorRouteImport.update({
  id: '/score-calculator',
  path: '/score-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YakuIndexRoute = YakuIndexRouteImport.update({
  id: '/yaku/',
  path: '/yaku/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const YakuIdRoute = YakuIdRouteImport.update({
  id: '/yaku/$id',
  path: '/yaku/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizPlayRoute = QuizPlayRouteImport.update({
  id: '/quiz/play',
  path: '/quiz/play',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizHistoryRoute = QuizHistoryRouteImport.update({
  id: '/quiz/history',
  path: '/quiz/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/score-calculator': typeof ScoreCalculatorRoute
  '/quiz/history': typeof QuizHistoryRoute
  '/quiz/play': typeof QuizPlayRoute
  '/yaku/$id': typeof YakuIdRoute
  '/quiz/': typeof QuizIndexRoute
  '/yaku/': typeof YakuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/score-calculator': typeof ScoreCalculatorRoute
  '/quiz/history': typeof QuizHistoryRoute
  '/quiz/play': typeof QuizPlayRoute
  '/yaku/$id': typeof YakuIdRoute
  '/quiz': typeof QuizIndexRoute
  '/yaku': typeof YakuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/score-calculator': typeof ScoreCalculatorRoute
  '/quiz/history': typeof QuizHistoryRoute
  '/quiz/play': typeof QuizPlayRoute
  '/yaku/$id': typeof YakuIdRoute
  '/quiz/': typeof QuizIndexRoute
  '/yaku/': typeof YakuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/ranking'
    | '/score-calculator'
    | '/quiz/history'
    | '/quiz/play'
    | '/yaku/$id'
    | '/quiz/'
    | '/yaku/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/ranking'
    | '/score-calculator'
    | '/quiz/history'
    | '/quiz/play'
    | '/yaku/$id'
    | '/quiz'
    | '/yaku'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/ranking'
    | '/score-calculator'
    | '/quiz/history'
    | '/quiz/play'
    | '/yaku/$id'
    | '/quiz/'
    | '/yaku/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  ScoreCalculatorRoute: typeof ScoreCalculatorRoute
  QuizHistoryRoute: typeof QuizHistoryRoute
  QuizPlayRoute: typeof QuizPlayRoute
  YakuIdRoute: typeof YakuIdRoute
  QuizIndexRoute: typeof QuizIndexRoute
  YakuIndexRoute: typeof YakuIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/score-calculator': {
      id: '/score-calculator'
      path: '/score-calculator'
      fullPath: '/score-calculator'
      preLoaderRoute: typeof ScoreCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaku/': {
      id: '/yaku/'
      path: '/yaku'
      fullPath: '/yaku/'
      preLoaderRoute: typeof YakuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaku/$id': {
      id: '/yaku/$id'
      path: '/yaku/$id'
      fullPath: '/yaku/$id'
      preLoaderRoute: typeof YakuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/play': {
      id: '/quiz/play'
      path: '/quiz/play'
      fullPath: '/quiz/play'
      preLoaderRoute: typeof QuizPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/history': {
      id: '/quiz/history'
      path: '/quiz/history'
      fullPath: '/quiz/history'
      preLoaderRoute: typeof QuizHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  ScoreCalculatorRoute: ScoreCalculatorRoute,
  QuizHistoryRoute: QuizHistoryRoute,
  QuizPlayRoute: QuizPlayRoute,
  YakuIdRoute: YakuIdRoute,
  QuizIndexRoute: QuizIndexRoute,
  YakuIndexRoute: YakuIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
