import { db } from "./index";
import { quizQuestion, quizQuestionYaku, yaku } from "./schema";

const now = new Date();

const yakuSeedData = [
  // === 一般役 ===
  {
    id: "riichi",
    nameJa: "立直",
    nameReading: "りーち",
    nameEn: "Riichi",
    han: 1,
    hanOpen: null,
    isYakuman: false,
    category: "normal" as const,
    description: "門前の手牌でテンパイになった際に宣言できる役。",
    conditions: JSON.stringify(["門前のみ", "テンパイ時に宣言", "1000点を供託"]),
    examples: JSON.stringify(["2m3m4m 5p6p7p 8s8s 東東東 (立直宣言後)"]),
    sortOrder: 1,
  },
  {
    id: "tanyao",
    nameJa: "断么九",
    nameReading: "たんやおちゅー",
    nameEn: "All Simples",
    han: 1,
    hanOpen: 1,
    isYakuman: false,
    category: "normal" as const,
    description: "1・9・字牌を使わず、2〜8の数牌のみで構成した役。",
    conditions: JSON.stringify(["手牌に1・9・字牌を使わない", "副露可"]),
    examples: JSON.stringify(["2m3m4m 5p6p7p 3s4s5s 2z2z 8m (ロン)"]),
    sortOrder: 2,
  },
  {
    id: "pinfu",
    nameJa: "平和",
    nameReading: "ぴんふ",
    nameEn: "All Sequences",
    han: 1,
    hanOpen: null,
    isYakuman: false,
    category: "normal" as const,
    description: "すべて順子で構成し、雀頭が役牌でなく、両面待ちで和了る役。",
    conditions: JSON.stringify(["門前のみ", "すべて順子", "雀頭が役牌以外", "両面待ち"]),
    examples: JSON.stringify(["1m2m3m 4p5p6p 7s8s9s 2z2z 6p (両面ロン)"]),
    sortOrder: 3,
  },
  {
    id: "ippatsu",
    nameJa: "一発",
    nameReading: "いっぱつ",
    nameEn: "Ippatsu",
    han: 1,
    hanOpen: null,
    isYakuman: false,
    category: "normal" as const,
    description: "立直宣言後、次の自分のツモまでの間に和了した場合に付く役。",
    conditions: JSON.stringify(["立直と同時に成立", "門前のみ", "立直後最初の巡で和了"]),
    examples: JSON.stringify(["立直後1巡以内に和了"]),
    sortOrder: 4,
  },
  {
    id: "menzen_tsumo",
    nameJa: "門前清自摸和",
    nameReading: "めんぜんつも",
    nameEn: "Menzen Tsumo",
    han: 1,
    hanOpen: null,
    isYakuman: false,
    category: "normal" as const,
    description: "門前でツモ和了した場合に付く役。",
    conditions: JSON.stringify(["門前のみ", "ツモ和了"]),
    examples: JSON.stringify(["門前手牌をツモ和了"]),
    sortOrder: 5,
  },
  {
    id: "iipeiko",
    nameJa: "一盃口",
    nameReading: "いーぺーこー",
    nameEn: "Pure Double Sequences",
    han: 1,
    hanOpen: null,
    isYakuman: false,
    category: "normal" as const,
    description: "同じ種類・同じ数の順子を2組持つ役。",
    conditions: JSON.stringify(["門前のみ", "同じ順子が2つ"]),
    examples: JSON.stringify(["1m2m3m 1m2m3m 4p5p6p 7s7s (ロン)"]),
    sortOrder: 6,
  },
  {
    id: "yakuhai",
    nameJa: "役牌",
    nameReading: "やくはい",
    nameEn: "Value Tiles",
    han: 1,
    hanOpen: 1,
    isYakuman: false,
    category: "normal" as const,
    description: "三元牌(中・発・白)または場風牌・自風牌で刻子を作った役。",
    conditions: JSON.stringify(["三元牌または場風・自風の刻子", "副露可"]),
    examples: JSON.stringify(["中中中 5p6p7p 3s4s5s 2m3m4m 1z (ロン)"]),
    sortOrder: 7,
  },
  {
    id: "tanyao_pinfu",
    nameJa: "断么九＋平和",
    nameReading: "たんやおぴんふ",
    nameEn: "Tanyao + Pinfu",
    han: 2,
    hanOpen: null,
    isYakuman: false,
    category: "normal" as const,
    description: "断么九と平和を同時に満たした複合役。",
    conditions: JSON.stringify(["断么九の条件を満たす", "平和の条件を満たす", "門前のみ"]),
    examples: JSON.stringify(["2m3m4m 5p6p7p 3s4s5s 8s8s 6p (両面ロン)"]),
    sortOrder: 8,
  },
  {
    id: "sanshoku_doujun",
    nameJa: "三色同順",
    nameReading: "さんしょくどうじゅん",
    nameEn: "Mixed Triple Sequences",
    han: 2,
    hanOpen: 1,
    isYakuman: false,
    category: "normal" as const,
    description: "萬子・筒子・索子で同じ数字の順子を1つずつ作る役。",
    conditions: JSON.stringify(["3種類の数牌で同じ順子", "副露で1翻下がる"]),
    examples: JSON.stringify(["1m2m3m 1p2p3p 1s2s3s 東東東 5m (ロン)"]),
    sortOrder: 9,
  },
  {
    id: "ittsu",
    nameJa: "一気通貫",
    nameReading: "いっきつうかん",
    nameEn: "Pure Straight",
    han: 2,
    hanOpen: 1,
    isYakuman: false,
    category: "normal" as const,
    description: "同一の数牌で1〜9の順子3つを作る役。",
    conditions: JSON.stringify(["同じ数牌で1-2-3, 4-5-6, 7-8-9の順子", "副露で1翻下がる"]),
    examples: JSON.stringify(["1m2m3m 4m5m6m 7m8m9m 3p3p 2s (ロン)"]),
    sortOrder: 10,
  },
  {
    id: "chanta",
    nameJa: "混全帯么九",
    nameReading: "ちゃんた",
    nameEn: "Terminal or Honor in Each Set",
    han: 2,
    hanOpen: 1,
    isYakuman: false,
    category: "normal" as const,
    description: "すべての面子・雀頭に1・9・字牌が含まれる役。",
    conditions: JSON.stringify(["全面子と雀頭に1・9・字牌を含む", "副露で1翻下がる"]),
    examples: JSON.stringify(["1m2m3m 7p8p9p 1s1s1s 中中 9m (ロン)"]),
    sortOrder: 11,
  },
  {
    id: "toitoi",
    nameJa: "対々和",
    nameReading: "といとい",
    nameEn: "All Pungs",
    han: 2,
    hanOpen: 2,
    isYakuman: false,
    category: "normal" as const,
    description: "すべて刻子で構成する役。",
    conditions: JSON.stringify(["すべて刻子（槓子含む）", "副露可"]),
    examples: JSON.stringify(["3m3m3m 5p5p5p 7s7s7s 東東東 9m (ロン)"]),
    sortOrder: 12,
  },
  {
    id: "sanankou",
    nameJa: "三暗刻",
    nameReading: "さんあんこう",
    nameEn: "Three Concealed Pungs",
    han: 2,
    hanOpen: 2,
    isYakuman: false,
    category: "normal" as const,
    description: "暗刻を3つ持つ役。",
    conditions: JSON.stringify(["暗刻が3つ"]),
    examples: JSON.stringify(["3m3m3m 5p5p5p 7s7s7s 東東 (ツモ or 刻子待ちロン)"]),
    sortOrder: 13,
  },
  {
    id: "honitsu",
    nameJa: "混一色",
    nameReading: "ほんいつ",
    nameEn: "Half Flush",
    han: 3,
    hanOpen: 2,
    isYakuman: false,
    category: "normal" as const,
    description: "1種類の数牌と字牌だけで構成した役。",
    conditions: JSON.stringify(["1種類の数牌と字牌のみ", "副露で1翻下がる"]),
    examples: JSON.stringify(["1m2m3m 4m5m6m 東東東 北北 9m (ロン)"]),
    sortOrder: 14,
  },
  {
    id: "junchan",
    nameJa: "純全帯么九",
    nameReading: "じゅんちゃんた",
    nameEn: "Terminals in All Sets",
    han: 3,
    hanOpen: 2,
    isYakuman: false,
    category: "normal" as const,
    description: "すべての面子・雀頭に1か9の数牌が含まれる役。字牌は不可。",
    conditions: JSON.stringify(["全面子と雀頭に1・9の数牌を含む", "字牌不可", "副露で1翻下がる"]),
    examples: JSON.stringify(["1m2m3m 7p8p9p 1s1s1s 9m9m 7m (ロン)"]),
    sortOrder: 15,
  },
  {
    id: "ryanpeiko",
    nameJa: "二盃口",
    nameReading: "りゃんぺーこー",
    nameEn: "Twice Pure Double Sequences",
    han: 3,
    hanOpen: null,
    isYakuman: false,
    category: "normal" as const,
    description: "一盃口を2組持つ役。",
    conditions: JSON.stringify(["門前のみ", "同じ順子が2組×2"]),
    examples: JSON.stringify(["1m2m3m 1m2m3m 4p5p6p 4p5p6p 9s9s (ロン)"]),
    sortOrder: 16,
  },
  {
    id: "chinitsu",
    nameJa: "清一色",
    nameReading: "ちんいつ",
    nameEn: "Full Flush",
    han: 6,
    hanOpen: 5,
    isYakuman: false,
    category: "normal" as const,
    description: "1種類の数牌だけで構成した役。",
    conditions: JSON.stringify(["1種類の数牌のみ", "副露で1翻下がる"]),
    examples: JSON.stringify(["1m2m3m 4m5m6m 7m8m9m 3m3m 1m (ロン)"]),
    sortOrder: 17,
  },
  {
    id: "chiitoi",
    nameJa: "七対子",
    nameReading: "ちーとーつ",
    nameEn: "Seven Pairs",
    han: 2,
    hanOpen: null,
    isYakuman: false,
    category: "normal" as const,
    description: "7種類の対子で構成した役。常に25符扱い。",
    conditions: JSON.stringify(["門前のみ", "7つの対子", "常に2翻25符"]),
    examples: JSON.stringify(["1m1m 3p3p 5s5s 東東 南南 西西 北北 (ツモ/ロン)"]),
    sortOrder: 18,
  },
  // === 役満 ===
  {
    id: "kokushi",
    nameJa: "国士無双",
    nameReading: "こくしむそう",
    nameEn: "Thirteen Orphans",
    han: 13,
    hanOpen: null,
    isYakuman: true,
    category: "yakuman" as const,
    description: "1m9m1p9p1s9s東南西北中発白の13種に加えてどれか1枚の対子。",
    conditions: JSON.stringify(["門前のみ", "19字牌13種＋1枚対子", "13面待ちは二倍役満"]),
    examples: JSON.stringify(["1m9m1p9p1s9s東南西北中発白 + 1種対子"]),
    sortOrder: 30,
  },
  {
    id: "suuankou",
    nameJa: "四暗刻",
    nameReading: "すーあんこう",
    nameEn: "Four Concealed Pungs",
    han: 13,
    hanOpen: null,
    isYakuman: true,
    category: "yakuman" as const,
    description: "暗刻を4つ持つ役満。単騎待ちは二倍役満。",
    conditions: JSON.stringify(["門前のみ", "暗刻が4つ", "単騎待ちは二倍役満"]),
    examples: JSON.stringify(["3m3m3m 5p5p5p 7s7s7s 東東東 9m (暗刻待ちツモ)"]),
    sortOrder: 31,
  },
  {
    id: "daisangen",
    nameJa: "大三元",
    nameReading: "だいさんげん",
    nameEn: "Big Three Dragons",
    han: 13,
    hanOpen: 13,
    isYakuman: true,
    category: "yakuman" as const,
    description: "三元牌（中・発・白）の刻子をすべて揃える役満。",
    conditions: JSON.stringify(["中・発・白の刻子をすべて作る", "副露可"]),
    examples: JSON.stringify(["中中中 発発発 白白白 1m2m3m 5p5p (ロン)"]),
    sortOrder: 32,
  },
  {
    id: "shosuushi",
    nameJa: "小四喜",
    nameReading: "しょうすーしー",
    nameEn: "Little Four Winds",
    han: 13,
    hanOpen: 13,
    isYakuman: true,
    category: "yakuman" as const,
    description: "東南西北のうち3つを刻子、1つを対子にする役満。",
    conditions: JSON.stringify(["東南西北のうち3つを刻子", "残り1つを雀頭（対子）", "副露可"]),
    examples: JSON.stringify(["東東東 南南南 西西西 北北 3m4m5m (ロン)"]),
    sortOrder: 33,
  },
  {
    id: "tsuuiisou",
    nameJa: "字一色",
    nameReading: "つーいーそう",
    nameEn: "All Honors",
    han: 13,
    hanOpen: 13,
    isYakuman: true,
    category: "yakuman" as const,
    description: "字牌のみで構成する役満。",
    conditions: JSON.stringify(["字牌のみ", "副露可"]),
    examples: JSON.stringify(["東東東 南南南 西西西 北北 中中 (ロン)"]),
    sortOrder: 34,
  },
  {
    id: "chinroutou",
    nameJa: "清老頭",
    nameReading: "ちんろうとう",
    nameEn: "All Terminals",
    han: 13,
    hanOpen: 13,
    isYakuman: true,
    category: "yakuman" as const,
    description: "1と9の数牌のみで構成する役満。",
    conditions: JSON.stringify(["1と9の数牌のみ", "副露可"]),
    examples: JSON.stringify(["1m1m1m 9m9m9m 1p1p1p 9p9p 1s (ロン)"]),
    sortOrder: 35,
  },
  {
    id: "ryuuiisou",
    nameJa: "緑一色",
    nameReading: "りゅーいーそう",
    nameEn: "All Green",
    han: 13,
    hanOpen: 13,
    isYakuman: true,
    category: "yakuman" as const,
    description: "2s・3s・4s・6s・8s・発だけで構成する役満。",
    conditions: JSON.stringify(["2s3s4s6s8s発のみ使用", "副露可"]),
    examples: JSON.stringify(["2s3s4s 6s6s6s 8s8s8s 発発発 2s2s (ロン)"]),
    sortOrder: 36,
  },
  {
    id: "suukantsu",
    nameJa: "四槓子",
    nameReading: "すーかんつ",
    nameEn: "Four Kongs",
    han: 13,
    hanOpen: 13,
    isYakuman: true,
    category: "yakuman" as const,
    description: "4回すべて槓をする役満。",
    conditions: JSON.stringify(["4つの槓子", "副露可"]),
    examples: JSON.stringify(["槓4回＋雀頭"]),
    sortOrder: 37,
  },
  {
    id: "tenhou",
    nameJa: "天和",
    nameReading: "てんほう",
    nameEn: "Blessing of Heaven",
    han: 13,
    hanOpen: null,
    isYakuman: true,
    category: "yakuman" as const,
    description: "親が配牌でそのまま和了する役満。",
    conditions: JSON.stringify(["親のみ", "配牌でテンパイかつ和了形"]),
    examples: JSON.stringify(["親の配牌時に和了形"]),
    sortOrder: 38,
  },
  {
    id: "chihou",
    nameJa: "地和",
    nameReading: "ちほう",
    nameEn: "Blessing of Earth",
    han: 13,
    hanOpen: null,
    isYakuman: true,
    category: "yakuman" as const,
    description: "子が第1ツモで和了する役満。",
    conditions: JSON.stringify(["子のみ", "第1ツモで和了"]),
    examples: JSON.stringify(["子の最初のツモで和了形"]),
    sortOrder: 39,
  },
];

// クイズ問題のシードデータ (点数計算済み)
const quizQuestionSeedData: Array<{
  id: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  han: number;
  fu: number;
  isOya: boolean;
  isTsumo: boolean;
  description: string;
  correctAnswer: number;
  choices: number[];
  yakuIds: string[];
}> = [
  // 初級 (beginner) — 1〜2翻
  {
    id: "q_b01",
    difficulty: "beginner",
    han: 1,
    fu: 30,
    isOya: false,
    isTsumo: false,
    description: "断么九 子のロン",
    correctAnswer: 1000,
    choices: [1000, 1300, 1500, 2000],
    yakuIds: ["tanyao"],
  },
  {
    id: "q_b02",
    difficulty: "beginner",
    han: 1,
    fu: 40,
    isOya: false,
    isTsumo: false,
    description: "立直 子のロン",
    correctAnswer: 1300,
    choices: [1000, 1300, 1500, 2000],
    yakuIds: ["riichi"],
  },
  {
    id: "q_b03",
    difficulty: "beginner",
    han: 2,
    fu: 30,
    isOya: false,
    isTsumo: false,
    description: "立直・断么九 子のロン",
    correctAnswer: 3900,
    choices: [2000, 3900, 5200, 7700],
    yakuIds: ["riichi", "tanyao"],
  },
  {
    id: "q_b04",
    difficulty: "beginner",
    han: 1,
    fu: 30,
    isOya: true,
    isTsumo: false,
    description: "立直 親のロン",
    correctAnswer: 3900,
    choices: [2900, 3900, 5800, 7700],
    yakuIds: ["riichi"],
  },
  {
    id: "q_b05",
    difficulty: "beginner",
    han: 2,
    fu: 40,
    isOya: false,
    isTsumo: false,
    description: "役牌・断么九 子のロン",
    correctAnswer: 5200,
    choices: [3900, 5200, 7700, 8000],
    yakuIds: ["yakuhai", "tanyao"],
  },
  {
    id: "q_b06",
    difficulty: "beginner",
    han: 1,
    fu: 30,
    isOya: false,
    isTsumo: true,
    description: "立直・門前清自摸和 子のツモ",
    correctAnswer: 500,
    choices: [300, 500, 700, 1000],
    yakuIds: ["riichi", "menzen_tsumo"],
  },
  {
    id: "q_b07",
    difficulty: "beginner",
    han: 2,
    fu: 30,
    isOya: true,
    isTsumo: false,
    description: "立直・平和 親のロン",
    correctAnswer: 7700,
    choices: [5800, 7700, 11600, 12000],
    yakuIds: ["riichi", "pinfu"],
  },
  {
    id: "q_b08",
    difficulty: "beginner",
    han: 1,
    fu: 50,
    isOya: false,
    isTsumo: false,
    description: "役牌 子のロン",
    correctAnswer: 1600,
    choices: [1300, 1600, 2000, 2400],
    yakuIds: ["yakuhai"],
  },
  {
    id: "q_b09",
    difficulty: "beginner",
    han: 2,
    fu: 50,
    isOya: false,
    isTsumo: false,
    description: "混全帯么九 子のロン (食い下がり1翻として扱う)",
    correctAnswer: 6400,
    choices: [3200, 4800, 6400, 8000],
    yakuIds: ["chanta"],
  },
  {
    id: "q_b10",
    difficulty: "beginner",
    han: 1,
    fu: 40,
    isOya: true,
    isTsumo: true,
    description: "門前清自摸和 親のツモ",
    correctAnswer: 1300,
    choices: [700, 1000, 1300, 2000],
    yakuIds: ["menzen_tsumo"],
  },
  // 中級 (intermediate) — 3〜4翻
  {
    id: "q_i01",
    difficulty: "intermediate",
    han: 3,
    fu: 30,
    isOya: false,
    isTsumo: false,
    description: "立直・断么九・平和 子のロン",
    correctAnswer: 7700,
    choices: [5200, 7700, 11600, 12000],
    yakuIds: ["riichi", "tanyao", "pinfu"],
  },
  {
    id: "q_i02",
    difficulty: "intermediate",
    han: 3,
    fu: 40,
    isOya: false,
    isTsumo: false,
    description: "混一色 子のロン",
    correctAnswer: 8000,
    choices: [5200, 7700, 8000, 12000],
    yakuIds: ["honitsu"],
  },
  {
    id: "q_i03",
    difficulty: "intermediate",
    han: 4,
    fu: 30,
    isOya: false,
    isTsumo: false,
    description: "一気通貫・断么九 子のロン",
    correctAnswer: 8000,
    choices: [7700, 8000, 11600, 12000],
    yakuIds: ["ittsu", "tanyao"],
  },
  {
    id: "q_i04",
    difficulty: "intermediate",
    han: 3,
    fu: 50,
    isOya: true,
    isTsumo: false,
    description: "三色同順 親のロン",
    correctAnswer: 12000,
    choices: [8000, 11600, 12000, 16000],
    yakuIds: ["sanshoku_doujun"],
  },
  {
    id: "q_i05",
    difficulty: "intermediate",
    han: 4,
    fu: 25,
    isOya: false,
    isTsumo: false,
    description: "七対子・立直 子のロン",
    correctAnswer: 8000,
    choices: [6400, 8000, 11600, 12000],
    yakuIds: ["chiitoi", "riichi"],
  },
  {
    id: "q_i06",
    difficulty: "intermediate",
    han: 3,
    fu: 30,
    isOya: true,
    isTsumo: true,
    description: "対々和 親のツモ",
    correctAnswer: 3900,
    choices: [2000, 3900, 4000, 6000],
    yakuIds: ["toitoi"],
  },
  {
    id: "q_i07",
    difficulty: "intermediate",
    han: 4,
    fu: 40,
    isOya: false,
    isTsumo: true,
    description: "立直・断么九・一発・ツモ 子のツモ",
    correctAnswer: 8000,
    choices: [5200, 7700, 8000, 12000],
    yakuIds: ["riichi", "tanyao", "ippatsu", "menzen_tsumo"],
  },
  {
    id: "q_i08",
    difficulty: "intermediate",
    han: 3,
    fu: 60,
    isOya: false,
    isTsumo: false,
    description: "混一色 子のロン (食い下がり)",
    correctAnswer: 8000,
    choices: [5800, 7700, 8000, 11600],
    yakuIds: ["honitsu"],
  },
  // 上級 (advanced) — 5翻以上・役満
  {
    id: "q_a01",
    difficulty: "advanced",
    han: 5,
    fu: 30,
    isOya: false,
    isTsumo: false,
    description: "清一色 子のロン (満貫)",
    correctAnswer: 8000,
    choices: [7700, 8000, 12000, 16000],
    yakuIds: ["chinitsu"],
  },
  {
    id: "q_a02",
    difficulty: "advanced",
    han: 7,
    fu: 30,
    isOya: false,
    isTsumo: false,
    description: "清一色・立直 子のロン (跳満)",
    correctAnswer: 12000,
    choices: [8000, 11600, 12000, 16000],
    yakuIds: ["chinitsu", "riichi"],
  },
  {
    id: "q_a03",
    difficulty: "advanced",
    han: 13,
    fu: 30,
    isOya: false,
    isTsumo: false,
    description: "国士無双 子のロン (役満)",
    correctAnswer: 32000,
    choices: [16000, 24000, 32000, 48000],
    yakuIds: ["kokushi"],
  },
  {
    id: "q_a04",
    difficulty: "advanced",
    han: 13,
    fu: 30,
    isOya: true,
    isTsumo: false,
    description: "四暗刻 親のロン (役満)",
    correctAnswer: 48000,
    choices: [24000, 32000, 48000, 64000],
    yakuIds: ["suuankou"],
  },
  {
    id: "q_a05",
    difficulty: "advanced",
    han: 9,
    fu: 30,
    isOya: false,
    isTsumo: false,
    description: "清一色・対々和 子のロン (倍満)",
    correctAnswer: 16000,
    choices: [12000, 16000, 24000, 32000],
    yakuIds: ["chinitsu", "toitoi"],
  },
  {
    id: "q_a06",
    difficulty: "advanced",
    han: 6,
    fu: 30,
    isOya: true,
    isTsumo: false,
    description: "清一色 親のロン (跳満)",
    correctAnswer: 18000,
    choices: [12000, 16000, 18000, 24000],
    yakuIds: ["chinitsu"],
  },
];

export async function seed() {
  console.log("シードデータを投入中...");

  // 役マスター
  const existingYaku = await db.select().from(yaku);
  if (existingYaku.length === 0) {
    await db.insert(yaku).values(
      yakuSeedData.map((y) => ({ ...y, createdAt: now, updatedAt: now })),
    );
    console.log(`役マスター: ${yakuSeedData.length}件 投入完了`);
  } else {
    console.log("役マスター: スキップ (既存データあり)");
  }

  // クイズ問題
  const existingQuestions = await db.select().from(quizQuestion);
  if (existingQuestions.length === 0) {
    for (const q of quizQuestionSeedData) {
      const { yakuIds, ...questionData } = q;
      await db.insert(quizQuestion).values({
        ...questionData,
        choices: JSON.stringify(questionData.choices),
        createdAt: now,
        updatedAt: now,
      });
      if (yakuIds.length > 0) {
        await db.insert(quizQuestionYaku).values(
          yakuIds.map((yakuId) => ({ questionId: q.id, yakuId })),
        );
      }
    }
    console.log(`クイズ問題: ${quizQuestionSeedData.length}件 投入完了`);
  } else {
    console.log("クイズ問題: スキップ (既存データあり)");
  }

  console.log("シード完了");
}
